import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Providers } from "./Providers";

export const metadata: Metadata = {
  title: "Product App",
  description: "Generated by Product App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Providers>
          <Header />
          <main className="flex-grow container mx-auto p-4 mt-[50px] mb-[50px]">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
